In [8]:
!pip install pandas as pd

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (3.0.6)

ERROR: Could not find a version that satisfies the requirement as (from versions: none)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for as

In [9]:
!pip install matplotlib as plt

Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (3.11.1)

ERROR: Could not find a version that satisfies the requirement as (from versions: none)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for as

In [4]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (2.5.1)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (2.5.1)
Requirement already satisfied: scipy in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (1.18.1)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
df = pd.read_csv('heart_disease_cleveland.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  target    303 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 33.3 KB

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

In [ ]:
#there is 4 ca with missing values and 2 thal with missing values

In [6]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [ ]:
# no need to drop any columns since all the columns are important for prediction

In [7]:
#filling the missing values with 'unknown'
df['ca'] = df['ca'].fillna('unknown')
df['thal'] = df['thal'].fillna('unknown')

In [9]:
print(df['target'].unique())

[0 1]

In [ ]:
# not need for binary target variable since the target variable is already binary(0,1)

In [10]:
#define the features and target variables
X = df.drop(columns= 'target')
y = df['target']

In [ ]:
#splitting the dataset into 80% training and 20% testing sets

from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(X,y, test_size = 0.2, random_state = 42)

In [13]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [14]:
# dividing the columns into numerical and categorical columns
numerical = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
categorical = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

In [15]:
X_train_numeric = X_train[numerical]
X_train_categoric = X_train[categorical]

In [17]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
scaler = StandardScaler()
X_train_numeric_scaled = scaler.fit_transform(X_train_numeric)
X_train_numeric_scaled = pd.DataFrame(X_train_numeric_scaled, columns = numerical)

# convert all categorical columns to string type
X_train_categoric = X_train_categoric.astype(str)
encoder = OneHotEncoder()
X_train_categoric_encoded = encoder.fit_transform(X_train_categoric)
X_train_categoric_encoded = pd.DataFrame(X_train_categoric_encoded.toarray(), columns = encoder.get_feature_names_out())

X_train_scaled_encoded = pd.concat([X_train_numeric_scaled, X_train_categoric_encoded], axis = 1)

In [19]:
X_test_numeric = X_test[numerical]
X_test_categoric = X_test[categorical]

X_test_numeric_scaled = scaler.transform(X_test_numeric)
X_test_numeric_scaled = pd.DataFrame(X_test_numeric_scaled, columns = numerical)

# convert all categorical columns to string type
X_test_categoric = X_test_categoric.astype(str)
X_test_categoric_encoded = encoder.transform(X_test_categoric)
X_test_categoric_encoded  = pd.DataFrame(X_test_categoric_encoded.toarray(), columns = encoder.get_feature_names_out())

X_test_scaled_encoded = pd.concat([X_test_numeric_scaled, X_test_categoric_encoded], axis = 1)

In [20]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state = 1)
model.fit(X_train_scaled_encoded, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report, roc_auc_score

y_pred = model.predict(X_test_scaled_encoded)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[26  3]
 [ 5 27]]
0.8688524590163934
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        29
           1       0.90      0.84      0.87        32

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

0.9
0.84375
0.8709677419354839
0.8701508620689655

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled_encoded, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report, roc_auc_score

y_pred = model.predict(X_test_scaled_encoded)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[24  5]
 [ 5 27]]
0.8360655737704918
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

0.84375
0.84375
0.84375
0.8356681034482758

In [23]:
from sklearn.svm import SVC

model = SVC(random_state =1)
model.fit(X_train_scaled_encoded, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report, roc_auc_score

y_pred = model.predict(X_test_scaled_encoded)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[26  3]
 [ 4 28]]
0.8852459016393442
              precision    recall  f1-score   support

           0       0.87      0.90      0.88        29
           1       0.90      0.88      0.89        32

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61

0.9032258064516129
0.875
0.8888888888888888
0.8857758620689655

In [24]:
from xgboost import XGBClassifier

model = XGBClassifier(random_state =1)
model.fit(X_train_scaled_encoded, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report, roc_auc_score

y_pred = model.predict(X_test_scaled_encoded)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[25  4]
 [ 6 26]]
0.8360655737704918
              precision    recall  f1-score   support

           0       0.81      0.86      0.83        29
           1       0.87      0.81      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

0.8666666666666667
0.8125
0.8387096774193549
0.8372844827586207